services:
  - type: web
    name: DOCHUB
    env: python3
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
